import { eachDayOfInterval, parseISO, format, subDays } from 'date-fns';
import type { Trip, TripEvent, MealPreferences } from '@/types';

interface EventToCreate {
  title: string;
  type: 'restaurant' | 'hotel' | 'transport';
  date: string;
  startTime: string;
  endTime: string;
  location: string;
  notes: string;
  cost: number;
  currency: string;
  attachments: string[];
  autoGenerated: boolean;
}

/**
 * Adds minutes to a time string (HH:MM) and returns a new HH:MM string.
 */
function addMinutesToTime(time: string, minutes: number): string {
  const [h, m] = time.split(':').map(Number);
  const totalMinutes = h * 60 + m + minutes;
  const newH = Math.floor(totalMinutes / 60) % 24;
  const newM = totalMinutes % 60;
  return `${String(newH).padStart(2, '0')}:${String(newM).padStart(2, '0')}`;
}

/**
 * Subtracts minutes from a (date, time) pair and returns the resulting
 * { date, time } — crossing into the previous day when the subtraction
 * goes before midnight. Returning the same day for an early-morning
 * flight (e.g. 01:00 → transfer at 22:30 the day before) pushed the
 * transfer event 12h AFTER the flight.
 */
function subtractMinutesFromDateTime(
  dateStr: string,
  time: string,
  minutes: number,
): { date: string; time: string } {
  const [h, m] = time.split(':').map(Number);
  let totalMinutes = h * 60 + m - minutes;
  let date = dateStr;
  while (totalMinutes < 0) {
    totalMinutes += 24 * 60;
    date = format(subDays(parseISO(date), 1), 'yyyy-MM-dd');
  }
  const newH = Math.floor(totalMinutes / 60) % 24;
  const newM = totalMinutes % 60;
  return {
    date,
    time: `${String(newH).padStart(2, '0')}:${String(newM).padStart(2, '0')}`,
  };
}

/**
 * Checks if two times are within a given number of minutes of each other.
 */
function timesAreClose(time1: string, time2: string, thresholdMinutes: number): boolean {
  const [h1, m1] = time1.split(':').map(Number);
  const [h2, m2] = time2.split(':').map(Number);
  const diff = Math.abs((h1 * 60 + m1) - (h2 * 60 + m2));
  return diff <= thresholdMinutes;
}

/**
 * Pure function that generates recurring events for a trip based on preferences.
 * Returns an array of event data objects ready to be created.
 */
export function generateRecurringEvents(
  trip: Trip,
  preferences: MealPreferences,
  existingEvents: TripEvent[],
): EventToCreate[] {
  const result: EventToCreate[] = [];
  const currency = trip.budgetCurrency || 'MXN';

  const start = parseISO(trip.startDate);
  const end = parseISO(trip.endDate);
  const days = eachDayOfInterval({ start, end });
  const lastDayStr = format(end, 'yyyy-MM-dd');

  for (const day of days) {
    const dateStr = format(day, 'yyyy-MM-dd');
    const dayEvents = existingEvents.filter((e) => e.date === dateStr);

    // --- Meals ---
    const mealSlots: Array<{ title: string; time: string }> = [
      { title: 'Desayuno', time: preferences.breakfast },
      { title: 'Comida', time: preferences.lunch },
      { title: 'Cena', time: preferences.dinner },
    ];

    for (const slot of mealSlots) {
      const hasExisting = dayEvents.some(
        (e) =>
          e.type === 'restaurant' &&
          e.startTime &&
          timesAreClose(e.startTime, slot.time, 90),
      );

      if (!hasExisting) {
        result.push({
          title: slot.title,
          type: 'restaurant',
          date: dateStr,
          startTime: slot.time,
          endTime: addMinutesToTime(slot.time, 60),
          location: '',
          notes: '',
          cost: preferences.defaultMealCost,
          currency,
          attachments: [],
          autoGenerated: true,
        });
      }
    }

    // --- Hotel (skip last day and days with cruise) ---
    if (dateStr !== lastDayStr) {
      const hasCruise = dayEvents.some((e) => e.type === 'cruise');
      const hasHotel = dayEvents.some((e) => e.type === 'hotel');

      if (!hasCruise && !hasHotel) {
        result.push({
          title: 'Hotel',
          type: 'hotel',
          date: dateStr,
          startTime: '21:00',
          endTime: '08:00',
          location: '',
          notes: '',
          cost: preferences.defaultHotelCost,
          currency,
          attachments: [],
          autoGenerated: true,
        });
      }
    }

    // --- Transfers based on flights ---
    const flightEvents = dayEvents.filter((e) => e.type === 'flight');

    for (const flight of flightEvents) {
      // Flight ARRIVES on this day
      const arrivalTime = flight.endTime || flight.details?.arrivalTime;
      if (arrivalTime && flight.date === dateStr) {
        // Check if this is an arrival (endTime exists or arrivalTime in details)
        const transferTime = addMinutesToTime(arrivalTime, 30);
        const hasTransportNear = dayEvents.some(
          (e) =>
            e.type === 'transport' &&
            e.startTime &&
            timesAreClose(e.startTime, transferTime, 90),
        );

        if (!hasTransportNear) {
          result.push({
            title: 'Traslado Aeropuerto → Hotel',
            type: 'transport',
            date: dateStr,
            startTime: transferTime,
            endTime: addMinutesToTime(transferTime, 60),
            location: '',
            notes: '',
            cost: preferences.defaultTransferCost,
            currency,
            attachments: [],
            autoGenerated: true,
          });
        }
      }

      // Flight DEPARTS on this day
      if (flight.startTime) {
        const { date: transferDate, time: transferTime } =
          subtractMinutesFromDateTime(dateStr, flight.startTime, 150);
        // When the transfer falls on the previous day we can't reliably
        // diff against the current day's events list — use the broader
        // existingEvents instead so we still skip dupes near the transfer.
        const candidateEvents = transferDate === dateStr
          ? dayEvents
          : existingEvents.filter((e) => e.date === transferDate);
        const hasTransportNear = candidateEvents.some(
          (e) =>
            e.type === 'transport' &&
            e.startTime &&
            timesAreClose(e.startTime, transferTime, 90),
        );

        if (!hasTransportNear) {
          result.push({
            title: 'Traslado Hotel → Aeropuerto',
            type: 'transport',
            date: transferDate,
            startTime: transferTime,
            endTime: addMinutesToTime(transferTime, 60),
            location: '',
            notes: '',
            cost: preferences.defaultTransferCost,
            currency,
            attachments: [],
            autoGenerated: true,
          });
        }
      }
    }
  }

  return result;
}
