/**
 * Firebase Storage upload for tripshistory photos.
 *
 * Generates 3 sizes (thumb 200 / medium 800 / full 2400 — longest side) and
 * uploads each in parallel. Resolves only when all 3 sizes are persisted and
 * we have download URLs for each. Callers can call this per file and accumulate
 * the resulting URLs into a PhotoMetadata payload.
 *
 * Storage layout:
 *   users/{userId}/tripstories/{storyId}/photos/{clientId}-{thumb|medium|full}.jpg
 */

import { ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { getClientStorage } from '@/lib/firebase/client';
import { isHeicFile, normalizeImageFile } from '@/lib/heic';

export interface UploadedPhotoUrls {
  thumbnailUrl: string;
  mediumUrl: string;
  fullUrl: string;
  /** Size of the largest blob actually uploaded (the "full" variant). */
  sizeBytes: number;
}

interface SizeSpec {
  label: 'thumb' | 'medium' | 'full';
  maxEdge: number;
  quality: number;
}

const SIZES: readonly SizeSpec[] = [
  { label: 'thumb', maxEdge: 200, quality: 0.75 },
  { label: 'medium', maxEdge: 800, quality: 0.82 },
  { label: 'full', maxEdge: 2400, quality: 0.88 },
] as const;

/* ─── Image resize helpers ─────────────────────────── */

async function loadImage(source: Blob): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    const url = URL.createObjectURL(source);
    const timeout = setTimeout(() => {
      URL.revokeObjectURL(url);
      reject(new Error('Image load timed out'));
    }, 30_000);
    img.onload = () => {
      clearTimeout(timeout);
      setTimeout(() => URL.revokeObjectURL(url), 0);
      resolve(img);
    };
    img.onerror = () => {
      clearTimeout(timeout);
      URL.revokeObjectURL(url);
      reject(new Error('Failed to decode image'));
    };
    img.src = url;
  });
}

function resizeToBlob(
  img: HTMLImageElement,
  maxEdge: number,
  quality: number,
): Promise<Blob> {
  return new Promise((resolve, reject) => {
    const w = img.naturalWidth || img.width;
    const h = img.naturalHeight || img.height;
    if (!w || !h) {
      reject(new Error('Image has no intrinsic dimensions'));
      return;
    }
    const longest = Math.max(w, h);
    const scale = longest > maxEdge ? maxEdge / longest : 1;
    const targetW = Math.max(1, Math.round(w * scale));
    const targetH = Math.max(1, Math.round(h * scale));

    const canvas = document.createElement('canvas');
    canvas.width = targetW;
    canvas.height = targetH;
    const ctx = canvas.getContext('2d');
    if (!ctx) {
      reject(new Error('Could not get 2D canvas context'));
      return;
    }
    ctx.drawImage(img, 0, 0, targetW, targetH);
    canvas.toBlob(
      (blob) => {
        if (blob) resolve(blob);
        else reject(new Error('Canvas toBlob returned null'));
      },
      'image/jpeg',
      quality,
    );
  });
}

/* ─── Public API ───────────────────────────────────── */

/**
 * Compress and upload a single photo into the story's Storage namespace.
 * Resolves only after all 3 sizes (thumb/medium/full) are persisted.
 *
 * The `clientId` is generated by the caller (so it can be paired with the
 * PhotoMetadata payload sent to the engine in the same request). We accept
 * it as a parameter rather than re-deriving here — that way two retries of
 * the same file end up at the same Storage paths and overwrite cleanly.
 */
export async function uploadPhotoToStory(
  file: File,
  storyId: string,
  userId: string,
  clientId: string,
): Promise<UploadedPhotoUrls> {
  if (!storyId) throw new Error('uploadPhotoToStory: missing storyId');
  if (!userId) throw new Error('uploadPhotoToStory: missing userId');
  if (!clientId) throw new Error('uploadPhotoToStory: missing clientId');

  const working: File = isHeicFile(file) ? await normalizeImageFile(file) : file;
  const img = await loadImage(working);
  const storage = getClientStorage();

  // Resize all three sizes in parallel.
  const blobs = await Promise.all(
    SIZES.map((s) => resizeToBlob(img, s.maxEdge, s.quality)),
  );

  // Upload all three in parallel.
  const refs = SIZES.map((s) =>
    ref(
      storage,
      `users/${userId}/tripstories/${storyId}/photos/${clientId}-${s.label}.jpg`,
    ),
  );
  await Promise.all(
    refs.map((r, i) =>
      uploadBytes(r, blobs[i], { contentType: 'image/jpeg' }),
    ),
  );

  const urls = await Promise.all(refs.map((r) => getDownloadURL(r)));
  const fullBlob = blobs[SIZES.findIndex((s) => s.label === 'full')];

  return {
    thumbnailUrl: urls[SIZES.findIndex((s) => s.label === 'thumb')],
    mediumUrl: urls[SIZES.findIndex((s) => s.label === 'medium')],
    fullUrl: urls[SIZES.findIndex((s) => s.label === 'full')],
    sizeBytes: fullBlob.size,
  };
}
