'use client';

import { useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { format, parseISO, differenceInDays, isAfter, isBefore, startOfDay } from 'date-fns';
import { formatDateHeaderES } from '@/lib/utils/helpers';
import {
  CalendarDays,
  Clock,
  MapPin,
  DollarSign,
  Plane,
  Hotel,
  UtensilsCrossed,
  Car,
  CarFront,
  Ship,
  MoreHorizontal,
  CalendarCheck,
  Sunset,
  Gift,
  Coffee,
  ShoppingBag,
  Fuel,
  Package,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
// Trip + events come from the layout-level TripDataProvider.
import {
  useTripFromContext as useTrip,
  useEventsFromContext as useEvents,
} from '@/context/TripDataContext';
import { EVENT_TYPES, ROUTES } from '@/config/constants';
import { classNames, formatCurrency } from '@/lib/utils/helpers';
import type { EventType } from '@/types';
import DailyDiaryCard from '@/components/diary/DailyDiaryCard';
import DailyHighlights from '@/components/highlights/DailyHighlights';
import TripDiaryHistory from '@/components/diary/TripDiaryHistory';
import ContextModeSwitcher from '@/components/trips/ContextModeSwitcher';
import { useAutoGenerateDiary } from '@/hooks/useAutoGenerateDiary';

/* ─── Icon map ─────────────────────────────────────── */

const ICON_MAP: Record<string, LucideIcon> = {
  Plane,
  Hotel,
  MapPin,
  UtensilsCrossed,
  Car,
  CarFront,
  Ship,
  MoreHorizontal,
  Gift,
  Coffee,
  ShoppingBag,
  Fuel,
  Package,
};

const BG_ICON_COLORS: Record<EventType, string> = {
  flight: 'bg-cyan-50 text-cyan-600',
  hotel: 'bg-violet-50 text-violet-600',
  car_rental: 'bg-yellow-50 text-yellow-600',
  activity: 'bg-green-50 text-green-600',
  restaurant: 'bg-orange-50 text-orange-600',
  transport: 'bg-blue-50 text-blue-600',
  cruise: 'bg-sky-50 text-sky-600',
  souvenirs: 'bg-pink-50 text-pink-600',
  snacks: 'bg-amber-50 text-amber-600',
  clothing: 'bg-rose-50 text-rose-600',
  fuel: 'bg-lime-50 text-lime-600',
  misc: 'bg-gray-50 text-gray-600',
};

const BORDER_COLORS: Record<EventType, string> = {
  flight: 'border-l-cyan-400',
  hotel: 'border-l-violet-400',
  car_rental: 'border-l-yellow-400',
  activity: 'border-l-green-400',
  restaurant: 'border-l-orange-400',
  transport: 'border-l-blue-400',
  cruise: 'border-l-sky-400',
  souvenirs: 'border-l-pink-400',
  snacks: 'border-l-amber-400',
  clothing: 'border-l-rose-400',
  fuel: 'border-l-lime-400',
  misc: 'border-l-gray-400',
};

/* ─── Component ────────────────────────────────────── */

export default function TodayPage() {
  const params = useParams();
  const tripId = params.tripId as string;

  const { trip, loading: tripLoading } = useTrip();
  const { events, loading: eventsLoading } = useEvents();

  const loading = tripLoading || eventsLoading;

  const todayStr = useMemo(() => {
    return format(new Date(), 'yyyy-MM-dd');
  }, []);

  const todayEvents = useMemo(() => {
    return events.filter((e) => e.date === todayStr);
  }, [events, todayStr]);

  const tripState = useMemo(() => {
    if (!trip) return 'loading';
    const today = startOfDay(new Date());
    const start = startOfDay(parseISO(trip.startDate));
    const end = startOfDay(parseISO(trip.endDate));

    if (isBefore(today, start)) {
      const days = differenceInDays(start, today);
      return { type: 'upcoming' as const, days };
    }
    if (isAfter(today, end)) {
      return { type: 'ended' as const };
    }
    const dayNumber = differenceInDays(today, start) + 1;
    const totalDays = differenceInDays(end, start) + 1;
    return { type: 'active' as const, dayNumber, totalDays };
  }, [trip]);

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="flex items-center justify-center py-20">
          <div className="w-8 h-8 border-2 border-gray-200 border-t-blue-400 rounded-full animate-spin" />
        </div>
      </div>
    );
  }

  if (!trip) {
    return (
      <div className="text-center py-20">
        <p className="text-gray-600">Viaje no encontrado</p>
      </div>
    );
  }

  const todayFormatted = formatDateHeaderES(format(new Date(), 'yyyy-MM-dd'));

  // Next upcoming event today, used by the active-state hero to surface
  // "what's next" without making the user scroll.
  const nowHHMM = format(new Date(), 'HH:mm');
  const nextEventToday = todayEvents
    .filter((e) => !e.startTime || e.startTime >= nowHHMM)
    .sort((a, b) => (a.startTime || '').localeCompare(b.startTime || ''))[0];

  const isActiveTrip = typeof tripState === 'object' && tripState.type === 'active';

  // Context-mode chips: surface aeropuerto / hotel / restaurante when the
  // trip is active AND there's a relevant event in the next 24h. We compute
  // the set of "near" event types so the switcher can highlight them; it
  // still renders all three chips so the user can jump manually.
  const nearEventTypes = useMemo(() => {
    const set = new Set<EventType>();
    if (!isActiveTrip) return set;
    const nowMs = Date.now();
    const windowMs = 24 * 60 * 60 * 1000;
    for (const e of events) {
      if (e.type !== 'flight' && e.type !== 'hotel' && e.type !== 'restaurant') continue;
      if (!e.date) continue;
      const [y, m, d] = e.date.split('-').map(Number);
      if (!y || !m || !d) continue;
      let h = 0;
      let min = 0;
      if (e.startTime) {
        const parts = e.startTime.split(':').map(Number);
        if (parts.length >= 2 && !Number.isNaN(parts[0]) && !Number.isNaN(parts[1])) {
          h = parts[0];
          min = parts[1];
        }
      }
      const ts = new Date(y, m - 1, d, h, min).getTime();
      const delta = ts - nowMs;
      // Hotels: include if check-out is in the future too (you're "in" the hotel).
      if (e.type === 'hotel') {
        const checkOut = e.details?.checkOutDate;
        const checkOutTime = e.details?.checkOutTime;
        if (checkOut) {
          const [cy, cm, cd] = checkOut.split('-').map(Number);
          if (cy && cm && cd) {
            let ch = 11;
            let cmin = 0;
            if (checkOutTime) {
              const cParts = checkOutTime.split(':').map(Number);
              if (cParts.length >= 2 && !Number.isNaN(cParts[0]) && !Number.isNaN(cParts[1])) {
                ch = cParts[0];
                cmin = cParts[1];
              }
            }
            const coTs = new Date(cy, cm - 1, cd, ch, cmin).getTime();
            if (coTs >= nowMs) {
              set.add(e.type);
              continue;
            }
          }
        }
      }
      if (delta >= -windowMs && delta <= windowMs) {
        set.add(e.type);
      }
    }
    return set;
  }, [events, isActiveTrip]);

  // Two-tab view: "Hoy" (today's events + diary editor) vs "Historia"
  // (all diary entries of the trip as a journal). We keep it as local
  // state so the user can flip without URL changes.
  const [activeTab, setActiveTab] = useState<'today' | 'history'>('today');

  // Backfill missing diary entries silently in the background. Runs once
  // per session per trip; covers active trips (so days you missed get
  // generated as you reopen) and past trips (so reopening an old trip
  // can still fill gaps you skipped at the time).
  const autogenEnabled =
    !!trip &&
    typeof tripState === 'object' &&
    (tripState.type === 'active' || tripState.type === 'ended');
  useAutoGenerateDiary({ trip, events, enabled: autogenEnabled });

  return (
    <div className="space-y-6">
      {/* Hero header — full bleed, photo background, big editorial type.
          Same component handles the three lifecycle modes (upcoming /
          active / ended) so the user always lands on a confident screen
          that tells them where they are in the trip. */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="relative overflow-hidden rounded-3xl"
        style={{
          minHeight: 220,
          background: isActiveTrip
            ? 'linear-gradient(135deg, #0d1320 0%, #1c2436 100%)'
            : 'linear-gradient(135deg, #fafaf7 0%, #f4ecd8 100%)',
        }}
      >
        {/* Destination cover photo, blurred + dimmed so type stays readable. */}
        {trip.coverImage && (
          <>
            <div
              aria-hidden="true"
              className="absolute inset-0 pointer-events-none"
              style={{
                backgroundImage: `url(${trip.coverImage})`,
                backgroundSize: 'cover',
                backgroundPosition: 'center',
                opacity: isActiveTrip ? 0.5 : 0.35,
                filter: 'brightness(0.85)',
              }}
            />
            <div
              aria-hidden="true"
              className="absolute inset-0 pointer-events-none"
              style={{
                background: isActiveTrip
                  ? 'linear-gradient(180deg, rgba(13,19,32,0.25) 0%, rgba(13,19,32,0.85) 100%)'
                  : 'linear-gradient(180deg, rgba(250,250,247,0.3) 0%, rgba(250,250,247,0.85) 100%)',
              }}
            />
          </>
        )}

        <div className="relative z-10 p-6 sm:p-8 flex flex-col h-full" style={{ minHeight: 220 }}>
          <div className="text-eyebrow" style={{ color: isActiveTrip ? '#ff9595' : '#1a3d62' }}>
            {typeof tripState === 'object' && tripState.type === 'active' && `Estás en ${trip.destination}`}
            {typeof tripState === 'object' && tripState.type === 'upcoming' && 'Tu próximo viaje'}
            {typeof tripState === 'object' && tripState.type === 'ended' && 'Tu último viaje'}
          </div>

          <h1
            className="text-hero mt-1"
            style={{ color: isActiveTrip ? '#f4f0e6' : '#1a1a1a' }}
          >
            {typeof tripState === 'object' && tripState.type === 'active' &&
              `Día ${tripState.dayNumber}`}
            {typeof tripState === 'object' && tripState.type === 'upcoming' &&
              (tripState.days === 0 ? 'Mañana arrancás' : `En ${tripState.days} días`)}
            {typeof tripState === 'object' && tripState.type === 'ended' && trip.title}
          </h1>

          <p
            className="text-sm mt-1.5"
            style={{ color: isActiveTrip ? 'rgba(244,240,230,0.7)' : 'rgba(26,26,26,0.65)' }}
          >
            {typeof tripState === 'object' && tripState.type === 'active' &&
              `de ${tripState.totalDays} · ${todayFormatted}`}
            {typeof tripState === 'object' && tripState.type === 'upcoming' &&
              `${trip.destination} · arranca el ${formatDateHeaderES(trip.startDate)}`}
            {typeof tripState === 'object' && tripState.type === 'ended' &&
              `Volviste el ${formatDateHeaderES(trip.endDate)}`}
          </p>

          {/* Next-up chip — active only, surfaces the imminent event */}
          {isActiveTrip && nextEventToday && (
            <div
              className="mt-auto pt-5 inline-flex items-center gap-2 rounded-xl px-3 py-2 self-start"
              style={{
                background: 'rgba(255,255,255,0.1)',
                backdropFilter: 'blur(8px)',
                color: '#f4f0e6',
              }}
            >
              <Clock className="w-3.5 h-3.5" style={{ color: '#ff9595' }} />
              <span className="text-xs font-semibold" style={{ color: '#ff9595' }}>
                {nextEventToday.startTime || 'En el día'}
              </span>
              <span className="text-xs opacity-80">·</span>
              <span className="text-xs font-medium truncate max-w-[200px]">
                {nextEventToday.title}
              </span>
            </div>
          )}
        </div>
      </motion.div>

      {/* Tabs: Hoy vs Historia (bitácora completa del viaje). The history
          tab lets the user reread the full diary as a journal, without
          leaving the trip context. */}
      <div className="flex items-center gap-1 p-1 bg-gray-100 rounded-xl w-fit">
        {[
          { key: 'today' as const, label: 'Hoy' },
          { key: 'history' as const, label: 'Historia' },
        ].map((tab) => {
          const active = activeTab === tab.key;
          return (
            <button
              key={tab.key}
              type="button"
              onClick={() => setActiveTab(tab.key)}
              className="px-4 py-1.5 rounded-lg text-xs font-bold transition-all"
              style={
                active
                  ? { background: '#1a1a1a', color: '#fff' }
                  : { background: 'transparent', color: '#6b7280' }
              }
            >
              {tab.label}
            </button>
          );
        })}
      </div>

      {/* HISTORY TAB — full diary journal */}
      {activeTab === 'history' && (
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.25 }}
        >
          <TripDiaryHistory
            tripId={tripId}
            tripStartDate={trip.startDate}
            tripEndDate={trip.endDate}
          />
        </motion.div>
      )}

      {/* Everything below is the TODAY tab. Wrapped so we can hide it
          when the user switches to Historia without unmounting the
          underlying data subscriptions (they live in the page-level
          hooks above). */}
      {activeTab === 'today' && (
      <>

      {/* Quick action chips — same set across all states so the layout
          stays predictable. Each tap routes to the matching trip section. */}
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.15 }}
        className="flex flex-wrap gap-2"
      >
        <Link
          href={ROUTES.app.trip(tripId) + '/itinerary'}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white border border-gray-200 hover:border-amber-300 hover:bg-amber-50 text-gray-700 text-xs font-semibold transition-colors"
        >
          <CalendarDays className="w-3.5 h-3.5" />
          Itinerario
        </Link>
        <Link
          href={ROUTES.app.trip(tripId) + '/expenses'}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white border border-gray-200 hover:border-emerald-300 hover:bg-emerald-50 text-gray-700 text-xs font-semibold transition-colors"
        >
          <DollarSign className="w-3.5 h-3.5" />
          Gastos
        </Link>
        <Link
          href={ROUTES.app.trip(tripId) + '/map'}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white border border-gray-200 hover:border-sky-300 hover:bg-sky-50 text-gray-700 text-xs font-semibold transition-colors"
        >
          <MapPin className="w-3.5 h-3.5" />
          Mapa
        </Link>
        <Link
          href={ROUTES.app.trip(tripId) + '/photos'}
          className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-white border border-gray-200 hover:border-rose-300 hover:bg-rose-50 text-gray-700 text-xs font-semibold transition-colors"
        >
          <Gift className="w-3.5 h-3.5" />
          Fotos
        </Link>
      </motion.div>

      {/* Trip state banners (legacy) — show only when not active so the
          new hero handles the active flow on its own. */}
      {typeof tripState === 'object' && tripState.type === 'upcoming' && (
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center py-16"
        >
          <div className="relative inline-flex items-center justify-center mb-6">
            <div className="absolute w-24 h-24 bg-amber-50 rounded-full" />
            <div className="relative w-20 h-20 bg-gray-100 rounded-2xl flex items-center justify-center">
              <CalendarCheck className="w-10 h-10 text-amber-400/60" />
            </div>
          </div>
          <h3 className="text-gray-700 text-lg font-bold mb-2">
            Faltan {tripState.days} {tripState.days === 1 ? 'dia' : 'dias'}
          </h3>
          <p className="text-gray-400 text-sm max-w-xs mx-auto mb-4">
            Tu viaje a <span className="text-gray-600 font-medium">{trip.destination}</span> comienza el{' '}
            {formatDateHeaderES(trip.startDate)}
          </p>
          <Link
            href={ROUTES.app.trip(tripId) + '/itinerary'}
            className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-500 text-sm font-medium transition-colors"
          >
            <CalendarDays className="w-4 h-4" />
            Ver itinerario
          </Link>
        </motion.div>
      )}

      {typeof tripState === 'object' && tripState.type === 'ended' && (
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          className="text-center py-16"
        >
          <div className="relative inline-flex items-center justify-center mb-6">
            <div className="absolute w-24 h-24 bg-blue-50 rounded-full" />
            <div className="relative w-20 h-20 bg-gray-100 rounded-2xl flex items-center justify-center">
              <Sunset className="w-10 h-10 text-blue-400/60" />
            </div>
          </div>
          <h3 className="text-gray-700 text-lg font-bold mb-2">
            Este viaje ya termino
          </h3>
          <p className="text-gray-400 text-sm max-w-xs mx-auto mb-4">
            Tu viaje a <span className="text-gray-600 font-medium">{trip.destination}</span> finalizo el{' '}
            {formatDateHeaderES(trip.endDate)}
          </p>
          <Link
            href={ROUTES.app.trip(tripId) + '/itinerary'}
            className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-500 text-sm font-medium transition-colors"
          >
            <CalendarDays className="w-4 h-4" />
            Ver itinerario completo
          </Link>
        </motion.div>
      )}

      {/* Active trip — list of today's events. The hero above already
          shows "Día N de M en <destino>" so we skip the redundant chip
          and jump straight to the agenda. */}
      {typeof tripState === 'object' && tripState.type === 'active' && (
        <>
          {/* Context-mode chips — only render when something relevant is
              in the next 24h. The switcher highlights the matching mode
              and routes to /mode/{key}. */}
          {nearEventTypes.size > 0 && (
            <motion.div
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="rounded-2xl p-4 mode-active"
              style={{ background: '#0d1320', border: '1px solid rgba(255,255,255,0.08)' }}
            >
              <div className="text-[10px] uppercase tracking-[0.18em] font-bold text-white/50 mb-2">
                Modos contextuales
              </div>
              <ContextModeSwitcher tripId={tripId} activeTypes={nearEventTypes} />
            </motion.div>
          )}

          {todayEvents.length === 0 ? (
            <motion.div
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1 }}
              className="text-center py-12"
            >
              <div className="relative inline-flex items-center justify-center mb-6">
                <div className="absolute w-20 h-20 bg-gray-50 rounded-full" />
                <div className="relative w-16 h-16 bg-gray-100 rounded-2xl flex items-center justify-center">
                  <CalendarDays className="w-8 h-8 text-blue-300" />
                </div>
              </div>
              <h3 className="text-gray-600 text-base font-semibold mb-2">
                Sin eventos para hoy
              </h3>
              <p className="text-gray-300 text-sm max-w-xs mx-auto mb-4">
                Aprovecha el dia libre o revisa el itinerario para agregar algo
              </p>
              <Link
                href={ROUTES.app.trip(tripId) + '/itinerary'}
                className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-500 text-sm font-medium transition-colors"
              >
                <CalendarDays className="w-4 h-4" />
                Revisar itinerario
              </Link>
            </motion.div>
          ) : (
            <div className="space-y-3">
              {todayEvents.map((event, index) => {
                const typeConfig = EVENT_TYPES[event.type];
                const Icon = ICON_MAP[typeConfig.icon] || MoreHorizontal;

                return (
                  <motion.div
                    key={event.id}
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.05 + index * 0.06 }}
                    className={classNames(
                      'glass rounded-xl border-l-4 p-4',
                      BORDER_COLORS[event.type],
                    )}
                  >
                    <div className="flex items-start gap-3">
                      <div
                        className={classNames(
                          'w-11 h-11 rounded-xl flex items-center justify-center flex-shrink-0',
                          BG_ICON_COLORS[event.type],
                        )}
                      >
                        <Icon className="w-5 h-5" />
                      </div>

                      <div className="flex-1 min-w-0">
                        <div className="flex items-start justify-between gap-2">
                          <div>
                            <h3 className="text-gray-900 font-semibold text-sm">
                              {event.title}
                            </h3>
                            <span
                              className="text-xs font-medium px-2 py-0.5 rounded-full inline-block mt-1"
                              style={{
                                backgroundColor: `${typeConfig.color}25`,
                                color: typeConfig.color,
                              }}
                            >
                              {typeConfig.label}
                            </span>
                          </div>
                          {event.cost > 0 && (
                            <span className="flex items-center gap-1 text-emerald-600 text-sm font-medium flex-shrink-0">
                              <DollarSign className="w-3.5 h-3.5" />
                              {formatCurrency(event.cost, event.currency)}
                            </span>
                          )}
                        </div>

                        <div className="mt-3 space-y-1.5">
                          {(event.startTime || event.endTime) && (
                            <p className="flex items-center gap-1.5 text-gray-600 text-xs">
                              <Clock className="w-3.5 h-3.5 flex-shrink-0 text-gray-300" />
                              {[event.startTime, event.endTime].filter(Boolean).join(' - ')}
                            </p>
                          )}
                          {event.location && (
                            <p className="flex items-center gap-1.5 text-gray-600 text-xs">
                              <MapPin className="w-3.5 h-3.5 flex-shrink-0 text-gray-300" />
                              {event.location}
                            </p>
                          )}
                        </div>

                        {event.notes && (
                          <p className="text-gray-400 text-xs mt-3 leading-relaxed">
                            {event.notes}
                          </p>
                        )}
                      </div>
                    </div>
                  </motion.div>
                );
              })}

              {/* Summary */}
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.3 }}
                className="pt-4 text-center"
              >
                <p className="text-gray-200 text-xs">
                  {todayEvents.length} {todayEvents.length === 1 ? 'evento' : 'eventos'} hoy
                </p>
              </motion.div>
            </div>
          )}

          {/* Daily diary — Gemini-generated summary the user can keep or
              edit. Only appears for active trips so we don't ask people
              to write a diary about a trip they haven't started. */}
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4 }}
            className="mt-2"
          >
            <DailyDiaryCard tripId={tripId} date={todayStr} />
          </motion.div>

          {/* Daily highlights — Gemini-curated top 3 photos of today.
              Sits just below the diary so the user gets text + photo
              recap in a single scroll. Active-trip only (same reason as
              the diary above). */}
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.45 }}
            className="mt-2"
          >
            <DailyHighlights tripId={tripId} date={todayStr} />
          </motion.div>
        </>
      )}

      </>
      )}
    </div>
  );
}
