'use client';

/**
 * Background diary auto-generation. Mounted on /today; runs once when
 * the user enters a trip, finds days that have already passed but don't
 * have a diary entry yet, and quietly generates them via /api/diary so
 * the user wakes up to a complete bitácora.
 *
 * Constraints kept deliberately tight to avoid wasted Gemini calls and
 * runaway costs:
 *   - Only trips that started ≤ today are processed (no pre-trip days).
 *   - Skip the current day — its diary is the user's tap (or end-of-day
 *     prompt later) so we don't spoil the editor for them.
 *   - Skip days with neither events nor expenses (nothing to narrate).
 *   - Skip days that already have an entry in trips/<id>/diary/<date>.
 *   - Process at most MAX_PER_SESSION days per session to keep the
 *     fan-out small if you open the app after a 5-day disconnect.
 *   - Mark a per-session sentinel so reopening /today inside the same
 *     session doesn't fire a second sweep.
 *
 * No retries on failure. The next time the user opens the app a fresh
 * session starts, the sentinel resets, and the missing day will be
 * tried again.
 */

import { useEffect } from 'react';
import { collection, getDocs } from 'firebase/firestore';
import { getClientAuth, getClientDb } from '@/lib/firebase/client';
import type { Trip, TripEvent } from '@/types';

const MAX_PER_SESSION = 3;
const SESSION_KEY = (tripId: string) => `gustrips:diary-autogen-tried:${tripId}`;

function toIsoLocal(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

function parseIsoLocal(s: string): Date | null {
  const [y, m, d] = (s || '').split('-').map(Number);
  if (!y || !m || !d) return null;
  return new Date(y, m - 1, d);
}

function daysBetweenInclusive(start: string, end: string): string[] {
  const s = parseIsoLocal(start);
  const e = parseIsoLocal(end);
  if (!s || !e || s > e) return [];
  const out: string[] = [];
  const cursor = new Date(s);
  while (cursor <= e) {
    out.push(toIsoLocal(cursor));
    cursor.setDate(cursor.getDate() + 1);
  }
  return out;
}

interface Args {
  trip: Trip | null | undefined;
  events: TripEvent[] | undefined;
  /** True iff diary autogen is appropriate (trip active or past). */
  enabled: boolean;
}

export function useAutoGenerateDiary({ trip, events, enabled }: Args): void {
  useEffect(() => {
    if (!enabled || !trip?.id || typeof window === 'undefined') return;

    const sessionKey = SESSION_KEY(trip.id);
    if (window.sessionStorage.getItem(sessionKey) === '1') {
      // Already attempted this trip in this session — don't sweep again
      // even if events refresh.
      return;
    }
    window.sessionStorage.setItem(sessionKey, '1');

    let cancelled = false;

    const run = async () => {
      const todayIso = toIsoLocal(new Date());
      const tripDays = daysBetweenInclusive(trip.startDate, trip.endDate)
        .filter((d) => d < todayIso); // strictly past — skip today

      if (tripDays.length === 0) return;

      // Group events by date for the "has content" check.
      const eventsByDate = new Map<string, number>();
      for (const ev of events || []) {
        if (!ev.date) continue;
        eventsByDate.set(ev.date, (eventsByDate.get(ev.date) || 0) + 1);
      }

      // We need to know which days already have a diary entry. One read
      // up-front beats one per day.
      const db = getClientDb();
      let existing: Set<string>;
      try {
        const diarySnap = await getDocs(collection(db, `trips/${trip.id}/diary`));
        existing = new Set(diarySnap.docs.map((d) => d.id));
      } catch (err) {
        console.warn('[diary-autogen] could not list existing diary entries', err);
        return;
      }

      // Same for expenses — Firestore doesn't let us cheaply query "where
      // date == X" across the subcollection multiple times, so we read
      // once and bucket.
      const expensesByDate = new Set<string>();
      try {
        const expSnap = await getDocs(collection(db, `trips/${trip.id}/expenses`));
        for (const d of expSnap.docs) {
          const data = d.data() as { date?: string; deletedAt?: unknown };
          if (data?.date && !data.deletedAt) expensesByDate.add(data.date);
        }
      } catch (err) {
        console.warn('[diary-autogen] could not list expenses', err);
        // Continue without expense data — we'll just rely on events.
      }

      // Candidates: past day, no existing diary, AND (has event OR has expense).
      const candidates = tripDays.filter((day) => {
        if (existing.has(day)) return false;
        const hasEvent = (eventsByDate.get(day) ?? 0) > 0;
        const hasExpense = expensesByDate.has(day);
        return hasEvent || hasExpense;
      });

      if (candidates.length === 0) return;

      // Newest gap first — if you open the app today, "ayer" is probably
      // what you'd notice if it were missing.
      candidates.sort((a, b) => b.localeCompare(a));

      // Get a fresh ID token once, reuse for the batch.
      const user = getClientAuth().currentUser;
      if (!user) return;
      let token: string;
      try {
        token = await user.getIdToken();
      } catch (err) {
        console.warn('[diary-autogen] no token', err);
        return;
      }

      let processed = 0;
      for (const day of candidates) {
        if (cancelled || processed >= MAX_PER_SESSION) break;
        try {
          // Fire and forget — the endpoint persists the entry server-side
          // by way of the client component, so we don't need its return.
          // Wait, actually /api/diary returns the text and the client
          // writes it. For autogen we want the same — but writing here
          // would skip the source: 'ai' tag. Easiest path: call the
          // endpoint, then write the doc ourselves with the same shape
          // DailyDiaryCard would.
          const res = await fetch('/api/diary', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              Authorization: `Bearer ${token}`,
            },
            body: JSON.stringify({ tripId: trip.id, date: day }),
          });
          if (!res.ok) {
            console.warn(`[diary-autogen] ${day} failed: ${res.status}`);
            continue;
          }
          const json = await res.json();
          if (!json?.ok || !json.content) {
            console.warn(`[diary-autogen] ${day} returned no content`);
            continue;
          }
          // Persist via the same path DailyDiaryCard uses.
          const { setDoc, doc, serverTimestamp } = await import('firebase/firestore');
          await setDoc(doc(db, 'trips', trip.id, 'diary', day), {
            content: json.content,
            generatedAt: new Date().toISOString(),
            source: 'ai',
            autoGenerated: true,
            updatedAt: serverTimestamp(),
          });
          processed += 1;
        } catch (err) {
          console.warn(`[diary-autogen] ${day} error`, err);
        }
      }
    };

    // Defer a bit so we don't race the page's initial paint.
    const t = window.setTimeout(() => { void run(); }, 1500);
    return () => {
      cancelled = true;
      window.clearTimeout(t);
    };
  }, [enabled, trip?.id, trip?.startDate, trip?.endDate, events]);
}
