import type { Timestamp } from 'firebase/firestore';

// ─── Trip ───────────────────────────────────────────
export type TripStatus = 'planning' | 'active' | 'completed' | 'cancelled';

export interface MealPreferences {
  breakfast: string;
  lunch: string;
  dinner: string;
  defaultMealCost: number;
  defaultHotelCost: number;
  defaultTransferCost: number;
}

export interface Trip {
  id: string;
  title: string;
  destination: string;
  startDate: string;
  endDate: string;
  description: string;
  coverImage: string | null;
  createdBy: string;
  createdAt: string;
  updatedAt: string;
  status: TripStatus;
  budget?: number;
  budgetCurrency?: string;
  shareToken?: string;
  budgetCategories?: BudgetCategory[];
  travelerIds?: string[];
  dayLocations?: Record<string, string>; // { "2026-05-10": "Southampton, England", "2026-05-11": "Portland, England" }
  albumPhotos?: AlbumPhoto[];
  mealPreferences?: MealPreferences;
  quickNotes?: QuickNote[];
  customLinks?: CustomLink[];
}

// ─── Custom Link ───────────────────────────────────
export type CustomLinkCategory =
  | 'vuelos'
  | 'hoteles'
  | 'autos'
  | 'restaurantes'
  | 'tours'
  | 'mapas'
  | 'seguros'
  | 'otros';

export interface CustomLink {
  id: string;
  name: string;
  url: string;
  category: CustomLinkCategory;
  createdAt: string;
}

// ─── Quick Note ───────────────────────────────────
export interface QuickNote {
  id: string;
  text: string;
  done: boolean;
  createdAt: string;
}

// ─── Album Photo ───────────────────────────────────
export interface AlbumPhoto {
  url: string;        // Thumbnail used in galleries (600px after optimization, legacy 1200px)
  fullUrl?: string;   // Full-quality version (cap 3000px, 92% JPEG) — used in lightbox
  optimized?: boolean; // True once the thumbnail has been re-compressed to 600px
  date: string;
  caption?: string;
  eventId?: string;
  uploadedAt: string;
}

// ─── Global Traveler ───────────────────────────────
export interface GlobalTraveler {
  id: string;
  fullName: string;
  relationship?: string;
  avatarColor?: string;
  dateOfBirth?: string;
  nationality?: string;
  phone?: string;
  emergencyContact?: string;
  emergencyPhone?: string;
  passportNumber?: string;
  passportCountry?: string;
  passportExpiry?: string;
  visaType?: string;
  visaCountry?: string;
  visaExpiry?: string;
  seatPreference?: 'window' | 'aisle' | 'middle' | '';
  dietaryRestrictions?: string;
  specialNeeds?: string;
  passportPhotoUrl?: string;
  visaPhotoUrl?: string;
  createdAt: string;
  updatedAt: string;
}

// ─── Member ─────────────────────────────────────────
export type MemberRole = 'owner' | 'editor' | 'viewer';

export interface TravelerInfo {
  // Personal
  fullName: string;
  dateOfBirth?: string;
  nationality?: string;
  phone?: string;
  emergencyContact?: string;
  emergencyPhone?: string;
  // Passport
  passportNumber?: string;
  passportCountry?: string;
  passportExpiry?: string;
  // Visa
  visaType?: string;
  visaCountry?: string;
  visaExpiry?: string;
  // Preferences
  seatPreference?: 'window' | 'aisle' | 'middle' | '';
  dietaryRestrictions?: string;
  specialNeeds?: string;
  // Documents
  passportPhotoUrl?: string;
  visaPhotoUrl?: string;
}

export interface TripMember {
  uid: string;
  email: string;
  displayName: string;
  role: MemberRole;
  joinedAt: string;
  invitedBy: string;
  travelerInfo?: TravelerInfo;
}

// ─── Invite ─────────────────────────────────────────
export type InviteStatus = 'pending' | 'accepted' | 'declined';

export interface TripInvite {
  id: string;
  email: string;
  role: MemberRole;
  status: InviteStatus;
  invitedBy: string;
  createdAt: string;
}

// ─── Event ──────────────────────────────────────────
export type EventType = 'flight' | 'hotel' | 'activity' | 'restaurant' | 'transport' | 'car_rental' | 'cruise' | 'souvenirs' | 'snacks' | 'clothing' | 'fuel' | 'misc';
export type ExpenseCategory = EventType;
export type PaymentMethod = 'cash' | 'debit' | 'credit' | 'transfer' | 'points' | 'other';

export interface TripEvent {
  id: string;
  title: string;
  type: EventType;
  date: string;
  startTime: string;
  endTime: string;
  location: string;
  city?: string; // City name for photos context
  country?: string; // Country name for photos context
  notes: string;
  cost: number;
  currency: string;
  attachments: string[];
  details?: Record<string, string>;
  latitude?: number;
  longitude?: number;
  timezone?: string; // IANA timezone, ej. "America/Mazatlan"
  photos?: string[]; // URLs of event photos (trip memories)
  autoGenerated?: boolean;
  /**
   * Free-form metadata attached by integrations.
   *
   * For events created by the Tripshistory engine (`autoGenerated: true`)
   * this contains `{ storyId, storyEventId, storyDayId }` so the UI can
   * map back to the originating story for inline question answering.
   */
  metadata?: {
    storyId?: string;
    storyEventId?: string;
    storyDayId?: string;
    [key: string]: unknown;
  };
  createdBy: string;
  createdAt: string;
}

// ─── Budget ─────────────────────────────────────────
export interface BudgetCategory {
  type: EventType;
  allocated: number;
}

export interface SharedExpense {
  id: string;
  eventId?: string;
  description: string;
  amount: number;
  currency: string;
  paidBy: string; // uid
  splitBetween: string[]; // uids
  date: string;
  createdAt: string;
}

export interface TripExpense {
  id: string;
  tripId: string;
  eventId?: string;
  description: string;
  amount: number;
  currency: string;
  category: ExpenseCategory;
  paidBy: string;
  splitBetween: string[];
  receiptUrl?: string;
  date: string;
  notes?: string;
  paymentMethod?: PaymentMethod;
  pointsUsed?: number;
  equivalentValue?: number;
  realValueCurrency?: string;
  settled?: boolean;
  createdAt: string;
  createdBy: string;
}

// ─── Attachment ─────────────────────────────────────
export type DocumentCategory =
  | 'flight'
  | 'hotel'
  | 'car_rental'
  | 'restaurant'
  | 'activity'
  | 'transport'
  | 'cruise'
  | 'insurance'
  | 'passport'
  | 'visa'
  | 'other';

export interface TripAttachment {
  id: string;
  name: string;
  url: string;
  type: string;
  size: number;
  uploadedBy: string;
  createdAt: string;
  eventId?: string;
  category?: DocumentCategory;
}

// ─── Checklist ──────────────────────────────────────
export type ChecklistPhase = 'pre-7d' | 'pre-1d' | 'airport' | 'hotel' | 'return';

export interface ChecklistItem {
  id: string;
  text: string;
  checked: boolean;
  phase: ChecklistPhase;
  createdBy: string;
  createdAt: string;
}

// ─── Activity Log ──────────────────────────────────
export interface ActivityLogEntry {
  id: string;
  action: 'created' | 'updated' | 'deleted';
  entityType: 'event' | 'checklist' | 'document' | 'member' | 'trip';
  entityName: string;
  userId: string;
  userName: string;
  createdAt: string;
}

// ─── User (minimal for auth) ────────────────────────
export interface AppUser {
  uid: string;
  email: string;
  displayName: string;
  photoURL: string | null;
}
