import type { ChecklistPhase } from '@/types';

export interface ChecklistTemplate {
  id: string;
  label: string;
  description: string;
  icon: string; // lucide icon name
  items: { text: string; phase: ChecklistPhase }[];
}

export const CHECKLIST_TEMPLATES: ChecklistTemplate[] = [
  {
    id: 'international',
    label: 'Viaje Internacional',
    description: 'Todo lo necesario para un viaje al extranjero',
    icon: 'Globe',
    items: [
      { text: 'Verificar vigencia del pasaporte (minimo 6 meses)', phase: 'pre-7d' },
      { text: 'Tramitar visa si es necesario', phase: 'pre-7d' },
      { text: 'Contratar seguro de viaje', phase: 'pre-7d' },
      { text: 'Revisar vacunas requeridas', phase: 'pre-7d' },
      { text: 'Notificar al banco sobre viaje', phase: 'pre-7d' },
      { text: 'Comprar adaptador de corriente', phase: 'pre-7d' },
      { text: 'Descargar mapas offline', phase: 'pre-7d' },
      { text: 'Activar roaming o comprar SIM local', phase: 'pre-1d' },
      { text: 'Imprimir confirmaciones de vuelo y hotel', phase: 'pre-1d' },
      { text: 'Preparar equipaje de mano', phase: 'pre-1d' },
      { text: 'Verificar peso de maletas', phase: 'pre-1d' },
      { text: 'Poner out of office en email', phase: 'pre-1d' },
      { text: 'Cargar dispositivos electronicos', phase: 'pre-1d' },
      { text: 'Llevar pasaporte y boarding pass', phase: 'airport' },
      { text: 'Llegar 3 horas antes al aeropuerto', phase: 'airport' },
      { text: 'Hacer check-in online', phase: 'airport' },
      { text: 'Pasar por migracion', phase: 'airport' },
      { text: 'Cambiar moneda o retirar efectivo', phase: 'airport' },
      { text: 'Verificar check-in del hotel', phase: 'hotel' },
      { text: 'Guardar objetos de valor en caja fuerte', phase: 'hotel' },
      { text: 'Conectar WiFi del hotel', phase: 'hotel' },
      { text: 'Revisar check-out del hotel', phase: 'return' },
      { text: 'Confirmar vuelo de regreso', phase: 'return' },
      { text: 'Empacar souvenirs y compras', phase: 'return' },
      { text: 'Verificar que no olvides nada en habitacion', phase: 'return' },
    ],
  },
  {
    id: 'beach',
    label: 'Playa / Resort',
    description: 'Para vacaciones en la playa',
    icon: 'Sun',
    items: [
      { text: 'Comprar bloqueador solar', phase: 'pre-7d' },
      { text: 'Empacar traje de bano', phase: 'pre-7d' },
      { text: 'Reservar actividades acuaticas', phase: 'pre-7d' },
      { text: 'Empacar lentes de sol y sombrero', phase: 'pre-1d' },
      { text: 'Llevar sandalias y zapatos de agua', phase: 'pre-1d' },
      { text: 'Empacar toalla de playa', phase: 'pre-1d' },
      { text: 'Llevar repelente de insectos', phase: 'pre-1d' },
      { text: 'Revisar horarios de alberca/playa', phase: 'hotel' },
      { text: 'Reservar camastros si aplica', phase: 'hotel' },
      { text: 'Revisar actividades del resort', phase: 'hotel' },
      { text: 'Secar trajes de bano antes de empacar', phase: 'return' },
      { text: 'Revisar arena en maletas', phase: 'return' },
    ],
  },
  {
    id: 'business',
    label: 'Viaje de Negocios',
    description: 'Para viajes corporativos',
    icon: 'Briefcase',
    items: [
      { text: 'Confirmar agenda de reuniones', phase: 'pre-7d' },
      { text: 'Preparar presentaciones', phase: 'pre-7d' },
      { text: 'Reservar transporte al venue', phase: 'pre-7d' },
      { text: 'Empacar ropa formal', phase: 'pre-1d' },
      { text: 'Cargar laptop y cargadores', phase: 'pre-1d' },
      { text: 'Llevar tarjetas de presentacion', phase: 'pre-1d' },
      { text: 'Descargar documentos offline', phase: 'pre-1d' },
      { text: 'Verificar WiFi en hotel de negocios', phase: 'hotel' },
      { text: 'Recopilar recibos para gastos', phase: 'return' },
      { text: 'Enviar follow-ups de reuniones', phase: 'return' },
    ],
  },
  {
    id: 'roadtrip',
    label: 'Road Trip',
    description: 'Para viajes en carretera',
    icon: 'Car',
    items: [
      { text: 'Revisar estado del vehiculo', phase: 'pre-7d' },
      { text: 'Verificar llantas y frenos', phase: 'pre-7d' },
      { text: 'Planear ruta y paradas', phase: 'pre-7d' },
      { text: 'Descargar musica/podcasts offline', phase: 'pre-7d' },
      { text: 'Llenar tanque de gasolina', phase: 'pre-1d' },
      { text: 'Empacar snacks y bebidas', phase: 'pre-1d' },
      { text: 'Llevar cargador de auto', phase: 'pre-1d' },
      { text: 'Llevar botiquin de primeros auxilios', phase: 'pre-1d' },
      { text: 'Verificar seguro del auto', phase: 'pre-1d' },
      { text: 'Revisar aceite y liquidos', phase: 'return' },
      { text: 'Limpiar el vehiculo', phase: 'return' },
    ],
  },
  {
    id: 'family',
    label: 'Viaje Familiar',
    description: 'Con ninos o familia extendida',
    icon: 'Heart',
    items: [
      { text: 'Verificar documentos de menores', phase: 'pre-7d' },
      { text: 'Empacar medicinas y botiquin', phase: 'pre-7d' },
      { text: 'Reservar asientos juntos en vuelo', phase: 'pre-7d' },
      { text: 'Investigar actividades para ninos', phase: 'pre-7d' },
      { text: 'Empacar juguetes y entretenimiento', phase: 'pre-1d' },
      { text: 'Llevar snacks para el viaje', phase: 'pre-1d' },
      { text: 'Empacar cambios de ropa extra', phase: 'pre-1d' },
      { text: 'Llevar carriola si es necesario', phase: 'airport' },
      { text: 'Pedir asistencia para familias en aeropuerto', phase: 'airport' },
      { text: 'Verificar cuna en hotel si aplica', phase: 'hotel' },
      { text: 'Revisar que no queden juguetes olvidados', phase: 'return' },
    ],
  },
];
