'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft } from 'lucide-react';
import { motion } from 'framer-motion';
import { addDays, parseISO, format, differenceInCalendarDays } from 'date-fns';
import {
  collection,
  doc,
  writeBatch,
} from 'firebase/firestore';
import { useTrips } from '@/hooks/useTrips';
import { useAuth } from '@/hooks/useAuth';
import { useToast } from '@/context/ToastContext';
import TripWizard, { type TripWizardData } from '@/components/trips/TripWizard';
import { ROUTES } from '@/config/constants';
import { nowISO } from '@/lib/utils/helpers';
import { getClientDb } from '@/lib/firebase/client';
import {
  TRIP_TEMPLATES,
  type TripTemplate,
} from '@/lib/tripTemplates';
import { PACKING_TEMPLATES } from '@/lib/packingTemplates';

/**
 * Clamp a daysFromStart offset so an event never lands past the trip's
 * last day. We still drop events that are clearly out of range
 * (e.g. a 7-day template applied to a 2-day trip — the late events get
 * collapsed onto the last day, which is the least-surprising behaviour).
 */
function dateForOffset(startISO: string, endISO: string, offset: number): string {
  const start = parseISO(startISO);
  const end = parseISO(endISO);
  const span = Math.max(0, differenceInCalendarDays(end, start));
  const clamped = Math.min(Math.max(0, offset), span);
  return format(addDays(start, clamped), 'yyyy-MM-dd');
}

/**
 * Seed a freshly-created trip with the template's events, checklist and
 * packing items. Everything goes in a single batch — Firestore caps
 * batches at 500 writes which is well above the largest template
 * (~25 packing + 6 checklist + 8 events ≈ 40 writes).
 */
async function seedTripFromTemplate(opts: {
  tripId: string;
  uid: string;
  startDate: string;
  endDate: string;
  template: TripTemplate;
}): Promise<void> {
  const { tripId, uid, startDate, endDate, template } = opts;
  const db = getClientDb();
  const batch = writeBatch(db);
  const createdAt = nowISO();

  // 1) Events
  const eventsCol = collection(db, `trips/${tripId}/events`);
  for (const ev of template.suggestedEvents) {
    const ref = doc(eventsCol);
    batch.set(ref, {
      title: ev.title,
      type: ev.type,
      date: dateForOffset(startDate, endDate, ev.daysFromStart),
      startTime: '',
      endTime: '',
      location: '',
      notes: ev.notes || '',
      cost: 0,
      currency: 'USD',
      attachments: [],
      autoGenerated: true,
      createdBy: uid,
      createdAt,
    });
  }

  // 2) Checklist defaults
  const checklistCol = collection(db, `trips/${tripId}/checklist`);
  for (const item of template.checklistDefaults) {
    const ref = doc(checklistCol);
    batch.set(ref, {
      text: item.text,
      checked: false,
      phase: item.phase,
      createdBy: uid,
      createdAt,
    });
  }

  // 3) Packing (from the linked packing template)
  const packing = PACKING_TEMPLATES[template.packingTemplate];
  if (packing) {
    const packingCol = collection(db, `trips/${tripId}/packing`);
    packing.items.forEach((it, idx) => {
      const ref = doc(packingCol);
      batch.set(ref, {
        name: it.name,
        category: it.category,
        quantity: it.quantity,
        optional: it.optional,
        packed: false,
        addedBy: uid,
        order: idx,
        createdAt,
      });
    });
  }

  await batch.commit();
}

export default function NewTripPage() {
  const router = useRouter();
  const { user } = useAuth();
  const { trips, createTrip } = useTrips();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);

  // Same reasoning as /trips/[tripId]/layout — router.back() is unreliable
  // when there's no usable history. Always go to the dashboard.
  const handleBack = () => {
    router.push(ROUTES.app.dashboard);
  };

  const handleComplete = async (data: TripWizardData) => {
    try {
      setLoading(true);
      const isFirstTrip = trips.length === 0;
      const tripId = await createTrip({
        title: data.title,
        destination: data.destination,
        startDate: data.startDate,
        endDate: data.endDate,
        description: '',
        status: 'planning',
        coverImage: null,
        travelerIds: data.travelerIds,
        // Budget is optional in the wizard — only set it when the user typed one.
        ...(data.budget !== undefined
          ? { budget: data.budget, budgetCurrency: data.budgetCurrency }
          : {}),
      });

      // If a template was picked, pre-fill the trip's events / checklist /
      // packing list BEFORE redirecting so the user lands on a populated trip.
      if (data.templateId && user?.uid) {
        const template: TripTemplate | undefined = TRIP_TEMPLATES[data.templateId];
        if (template) {
          try {
            await seedTripFromTemplate({
              tripId,
              uid: user.uid,
              startDate: data.startDate,
              endDate: data.endDate,
              template,
            });
            toast(`Plantilla "${template.label}" aplicada al viaje`, 'success');
          } catch (seedErr) {
            console.error('Error al aplicar la plantilla del viaje:', seedErr);
            // Non-fatal — the trip itself was created OK.
            toast('El viaje se creó, pero falló cargar la plantilla', 'info');
          }
        }
      }

      if (isFirstTrip) {
        toast('🎉 ¡Tu primer viaje está listo! Ahora agrega tu itinerario', 'success');
      } else {
        toast('Viaje creado exitosamente', 'success');
      }
      router.push(ROUTES.app.trip(tripId));
    } catch (err) {
      console.error('Error al crear viaje:', err);
      toast('Error al crear el viaje', 'error');
      setLoading(false);
    }
    // On success we navigate away, so we deliberately leave `loading` true
    // to keep the button disabled during the redirect.
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="flex items-center gap-3"
      >
        <button
          type="button"
          onClick={handleBack}
          aria-label="Volver"
          className="w-10 h-10 rounded-xl bg-white/[0.06] hover:bg-white/[0.1] flex items-center justify-center transition-colors border border-white/[0.06]"
        >
          <ArrowLeft className="w-5 h-5 text-white/80" />
        </button>
        <div>
          <h1 className="text-white text-2xl font-bold">Nuevo viaje</h1>
          <p className="text-white/55 text-sm">Respondé unas preguntas y te dejamos el viaje listo.</p>
        </div>
      </motion.div>

      <TripWizard loading={loading} onCancel={handleBack} onComplete={handleComplete} />
    </div>
  );
}
