'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, Sparkles, Check } from 'lucide-react';
import { motion } from 'framer-motion';
import { addDays, parseISO, format, differenceInCalendarDays } from 'date-fns';
import {
  collection,
  doc,
  writeBatch,
} from 'firebase/firestore';
import { useTrips } from '@/hooks/useTrips';
import { useAuth } from '@/hooks/useAuth';
import { useToast } from '@/context/ToastContext';
import TripForm from '@/components/trips/TripForm';
import { ROUTES } from '@/config/constants';
import { classNames, nowISO } from '@/lib/utils/helpers';
import { getClientDb } from '@/lib/firebase/client';
import {
  TRIP_TEMPLATE_LIST,
  TRIP_TEMPLATES,
  type TripTemplate,
  type TripTemplateId,
} from '@/lib/tripTemplates';
import { PACKING_TEMPLATES } from '@/lib/packingTemplates';

/** "Ninguno" sentinel so the chip group has a clean way to opt-out. */
const NO_TEMPLATE = '__none__' as const;
type SelectedTemplate = TripTemplateId | typeof NO_TEMPLATE | null;

/**
 * Clamp a daysFromStart offset so an event never lands past the trip's
 * last day. We still drop events that are clearly out of range
 * (e.g. a 7-day template applied to a 2-day trip — the late events get
 * collapsed onto the last day, which is the least-surprising behaviour).
 */
function dateForOffset(startISO: string, endISO: string, offset: number): string {
  const start = parseISO(startISO);
  const end = parseISO(endISO);
  const span = Math.max(0, differenceInCalendarDays(end, start));
  const clamped = Math.min(Math.max(0, offset), span);
  return format(addDays(start, clamped), 'yyyy-MM-dd');
}

/**
 * Seed a freshly-created trip with the template's events, checklist and
 * packing items. Everything goes in a single batch — Firestore caps
 * batches at 500 writes which is well above the largest template
 * (~25 packing + 6 checklist + 8 events ≈ 40 writes).
 */
async function seedTripFromTemplate(opts: {
  tripId: string;
  uid: string;
  startDate: string;
  endDate: string;
  template: TripTemplate;
}): Promise<void> {
  const { tripId, uid, startDate, endDate, template } = opts;
  const db = getClientDb();
  const batch = writeBatch(db);
  const createdAt = nowISO();

  // 1) Events
  const eventsCol = collection(db, `trips/${tripId}/events`);
  for (const ev of template.suggestedEvents) {
    const ref = doc(eventsCol);
    batch.set(ref, {
      title: ev.title,
      type: ev.type,
      date: dateForOffset(startDate, endDate, ev.daysFromStart),
      startTime: '',
      endTime: '',
      location: '',
      notes: ev.notes || '',
      cost: 0,
      currency: 'USD',
      attachments: [],
      autoGenerated: true,
      createdBy: uid,
      createdAt,
    });
  }

  // 2) Checklist defaults
  const checklistCol = collection(db, `trips/${tripId}/checklist`);
  for (const item of template.checklistDefaults) {
    const ref = doc(checklistCol);
    batch.set(ref, {
      text: item.text,
      checked: false,
      phase: item.phase,
      createdBy: uid,
      createdAt,
    });
  }

  // 3) Packing (from the linked packing template)
  const packing = PACKING_TEMPLATES[template.packingTemplate];
  if (packing) {
    const packingCol = collection(db, `trips/${tripId}/packing`);
    packing.items.forEach((it, idx) => {
      const ref = doc(packingCol);
      batch.set(ref, {
        name: it.name,
        category: it.category,
        quantity: it.quantity,
        optional: it.optional,
        packed: false,
        addedBy: uid,
        order: idx,
        createdAt,
      });
    });
  }

  await batch.commit();
}

export default function NewTripPage() {
  const router = useRouter();
  const { user } = useAuth();
  const { trips, createTrip } = useTrips();
  const { toast } = useToast();
  const [loading, setLoading] = useState(false);
  const [selectedTemplate, setSelectedTemplate] = useState<SelectedTemplate>(null);

  // Same reasoning as /trips/[tripId]/layout — router.back() is unreliable
  // when there's no usable history. Always go to the dashboard.
  const handleBack = () => {
    router.push(ROUTES.app.dashboard);
  };

  const handleSubmit = async (data: {
    title: string;
    destination: string;
    startDate: string;
    endDate: string;
    description?: string;
    status: 'planning' | 'active' | 'completed' | 'cancelled';
    coverImage?: string | null;
    travelerIds?: string[];
  }) => {
    try {
      setLoading(true);
      const isFirstTrip = trips.length === 0;
      const tripId = await createTrip({
        title: data.title,
        destination: data.destination,
        startDate: data.startDate,
        endDate: data.endDate,
        description: data.description || '',
        status: data.status,
        coverImage: data.coverImage ?? null,
        travelerIds: data.travelerIds || [],
      });

      // If a template was selected, pre-fill the trip's events / checklist
      // / packing list. We do this BEFORE redirecting so the user lands on
      // the trip page and sees the items already populated.
      if (selectedTemplate && selectedTemplate !== NO_TEMPLATE && user?.uid) {
        const template = TRIP_TEMPLATES[selectedTemplate];
        if (template) {
          try {
            await seedTripFromTemplate({
              tripId,
              uid: user.uid,
              startDate: data.startDate,
              endDate: data.endDate,
              template,
            });
            toast(`Plantilla "${template.label}" aplicada al viaje`, 'success');
          } catch (seedErr) {
            console.error('Error al aplicar la plantilla del viaje:', seedErr);
            // Non-fatal — the trip itself was created OK.
            toast('El viaje se creó, pero falló cargar la plantilla', 'info');
          }
        }
      }

      if (isFirstTrip) {
        toast('🎉 ¡Tu primer viaje está listo! Ahora agrega tu itinerario', 'success');
      } else {
        toast('Viaje creado exitosamente', 'success');
      }
      router.push(ROUTES.app.trip(tripId));
    } catch (err) {
      console.error('Error al crear viaje:', err);
      toast('Error al crear el viaje', 'error');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      {/* Header */}
      <motion.div
        initial={{ opacity: 0, y: -12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="flex items-center gap-3"
      >
        <button
          type="button"
          onClick={handleBack}
          aria-label="Volver"
          className="w-10 h-10 rounded-xl bg-white/[0.06] hover:bg-white/[0.1] flex items-center justify-center transition-colors border border-white/[0.06]"
        >
          <ArrowLeft className="w-5 h-5 text-white/80" />
        </button>
        <div>
          <h1 className="text-white text-2xl font-bold">Nuevo viaje</h1>
          <p className="text-white/55 text-sm">Cargá título, destino, fechas y construí el itinerario.</p>
        </div>
      </motion.div>

      <TripForm onSubmit={handleSubmit} loading={loading} />

      {/* Template picker — placed right under the form so the user sees
          it as a final "do you want a head start?" step before submitting.
          Selection survives multiple edits to the form above and only
          consumes time once `Crear Viaje` is pressed. */}
      <motion.section
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4, delay: 0.15 }}
        className="rounded-2xl p-5 bg-white border border-gray-200 shadow-sm"
      >
        <div className="flex items-start gap-3 mb-4">
          <div className="w-10 h-10 rounded-xl bg-amber-50 border border-amber-100 flex items-center justify-center flex-shrink-0">
            <Sparkles className="w-5 h-5 text-amber-500" />
          </div>
          <div className="flex-1">
            <h2 className="text-gray-900 text-base font-semibold">¿Qué tipo de viaje?</h2>
            <p className="text-gray-500 text-sm">
              Elegí una plantilla para pre-cargar el itinerario, el checklist y la maleta.
            </p>
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          {TRIP_TEMPLATE_LIST.map((tpl) => {
            const isSelected = selectedTemplate === tpl.id;
            return (
              <button
                key={tpl.id}
                type="button"
                onClick={() => setSelectedTemplate(isSelected ? null : tpl.id)}
                aria-pressed={isSelected}
                className={classNames(
                  'inline-flex items-center gap-2 px-3 py-2 rounded-xl border text-sm font-medium transition-all',
                  isSelected
                    ? 'bg-amber-50 border-amber-300 text-amber-700 shadow-sm'
                    : 'bg-white border-gray-200 text-gray-600 hover:bg-gray-50 hover:border-gray-300',
                )}
              >
                <span aria-hidden>{tpl.emoji}</span>
                <span>{tpl.label}</span>
                {isSelected && <Check className="w-3.5 h-3.5 text-amber-500" />}
              </button>
            );
          })}

          <button
            type="button"
            onClick={() => setSelectedTemplate(NO_TEMPLATE)}
            aria-pressed={selectedTemplate === NO_TEMPLATE}
            className={classNames(
              'inline-flex items-center gap-2 px-3 py-2 rounded-xl border text-sm font-medium transition-all',
              selectedTemplate === NO_TEMPLATE
                ? 'bg-gray-100 border-gray-400 text-gray-700'
                : 'bg-white border-gray-200 text-gray-500 hover:bg-gray-50 hover:border-gray-300',
            )}
          >
            Ninguno
          </button>
        </div>

        {selectedTemplate && selectedTemplate !== NO_TEMPLATE && (
          <p className="text-xs text-gray-500 mt-3">
            {TRIP_TEMPLATES[selectedTemplate].description}{' '}
            <span className="text-gray-400">
              ({TRIP_TEMPLATES[selectedTemplate].suggestedEvents.length} eventos,{' '}
              {TRIP_TEMPLATES[selectedTemplate].checklistDefaults.length} tareas,{' '}
              maleta {TRIP_TEMPLATES[selectedTemplate].packingTemplate})
            </span>
          </p>
        )}
      </motion.section>
    </div>
  );
}
